pipeline {
  agent any

  environment {
    IMAGE_NAME = "YOUR_DOCKERHUB_USERNAME/sample-flask"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    KUBE_NAMESPACE = "devops-demo"
  }

  stages {
    stage("Checkout") {
      steps { checkout scm }
    }

    stage("Build Image") {
      steps {
        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./app"
        sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest"
      }
    }

    stage("Push Image") {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DH_USER', passwordVariable: 'DH_PASS')]) {
          sh "echo $DH_PASS | docker login -u $DH_USER --password-stdin"
          sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
          sh "docker push ${IMAGE_NAME}:latest"
        }
      }
    }

    stage("Deploy to Kubernetes") {
      steps {
        sh """
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/service.yaml
          kubectl -n ${KUBE_NAMESPACE} set image deployment/sample-flask sample-flask=${IMAGE_NAME}:latest
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/servicemonitor.yaml
        """
      }
    }
  }
}
